server:
  servlet:
    context-path: /productcatalog
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pc_db
    username: slav
    password: slav
    driver-class-name: org.postgresql.Driver
    current-schema: pc_schema
#    dbcp2:
#      default-schema: productcatalog
  liquibase:
    url: jdbc:postgresql://localhost:5432/pc_db
    user: slav
    password: slav
    default-schema: pc_service_schema
    change-log: /db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.default_schema: pc_schema
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect